services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    restart: always
networks:
  default:
    external:
      name: test-network